@url = https://expensetracker-cchde4hcfbdud3gn.brazilsouth-01.azurewebsites.net

### 1. mesangem de boas-vindas
GET {{url}}

### 2. listar todas as transacoes
GET  {{url}}/transacoes

### 3. criar nova transacao
POST {{url}}/transacoes 
Content-Type: application/json

{
    "descricao": "Transacao",
    "valor": 5000,
    "categoria": "Lazer",
    "tipo": "despesa"
}
### 3.1 criar nova transacao
POST {{url}}/transacoes 
Content-Type: application/json

{
    "descricao": "Transacao",
    "valor": 2000,
    "categoria": "Salário",
    "tipo": "receita"
}

### OPCOES
# tipo: "receita" ou "despesa"
# RECEITAS_VALIDAS = ["Salário", "Freelance", "Vendas", "Outros"]
# DESPESAS_VALIDAS = ["Alimentação", "Transporte", "Lazer", "Contas", "Outros"]

### 4. buscar transacao por ID
GET {{url}}/transacoes/1

### 5. atualizar transacao
PUT {{url}}/transacoes/1
Content-Type: application/json

{
    "descricao": "alteracao de categoria",
    "categoria": "Contas"
}

### 5.1 atualizar transacao
PUT {{url}}/transacoes/1
Content-Type: application/json

{
    "descricao": "alteracao de valor",
    "valor": 2020
}

### 6. deletar transacao
DELETE {{url}}/transacao/1

### 7. buscar com filtros
GET {{url}}/transacao/buscar?tipo=despesa&categoria=Lazer

### 8. saldo atual
GET {{url}}/saldo

